#pragma once
namespace dune3d::IconTexture {
enum class IconTextureID{
  CONSTRAINT_POINTS_COINCIDENT,
  CONSTRAINT_HORIZONTAL,
  CONSTRAINT_VERTICAL,
  CONSTRAINT_PARALLEL,
  CONSTRAINT_EQUAL_LENGTH,
  CONSTRAINT_POINT_ON_LINE,
  CONSTRAINT_MIDPOINT,
  CONSTRAINT_WORKPLANE_NORMAL,
  CONSTRAINT_SAME_ORIENTATION,
  CONSTRAINT_POINT_ON_CIRCLE,
  CONSTRAINT_ARC_ARC_TANGENT,
  CONSTRAINT_ARC_LINE_TANGENT,
  CONSTRAINT_PERPENDICULAR,
  CONSTRAINT_POINT_IN_PLANE,
  CONSTRAINT_LOCK_ROTATION,
  CONSTRAINT_SYMMETRIC_HORIZONTAL,
  CONSTRAINT_SYMMETRIC_VERTICAL,
  CONSTRAINT_SYMMETRIC_LINE,
  CONSTRAINT_BEZIER_BEZIER_TANGENT_SYMMETRIC,
  CONSTRAINT_POINT_ON_BEZIER,
  POINT_BOX,
  POINT_CIRCLE,
  POINT_DIAMOND,
  POINT_CROSS,
  POINT_TRIANGLE_DOWN,
  CONSTRAINT_G2,
};


}
